// Code generated by go-swagger; DO NOT EDIT.

// Package restapi HighLoad Cup 2020
//
//  # IT RALLY 2020 HighLoad Cup
//  ## Usage
//  - The goal is to dig up and cash out treasures to increase your balance
//    as much as possible in fixed period of time (10 minutes).
//  - [Optional] Use /explore to find out where treasures were buried.
//  - Use /license to ensure you have valid license ID before calling /dig.
//    Each /dig call will increment license's DigUsed up to DigAllowed,
//    then this license will become inactive.
//  - Use /dig with Depth increasing serially from 1 to 10, and sometimes you'll
//    find a treasure.
//  - Use /cash on each treasure found by /dig to increase your balance.
//  - [Optional] You can pay for a license if you like to - this will
//    decrease your balance, but paid licenses have more DigAllowed, so
//    you'll have to issue less licenses.
//    Each coin in the wallet returned by /cash is unique, and may be spent to get
//    paid license just once.
//  - [Optional] You can get your current balance and coins using /balance, and your
//    current active licenses using /licenses.
//  ## List of all custom errors
//  First number is HTTP Status code, second is value of "code" field in returned JSON object, text description may or may not match "message" field in returned JSON object.
//  - 422.1000: wrong coordinates
//  - 422.1001: wrong depth
//  - 409.1002: no more active licenses allowed
//  - 409.1003: treasure is not digged
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.3.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
