// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// NewExploreAreaParams creates a new ExploreAreaParams object
// with the default values initialized.
func NewExploreAreaParams() *ExploreAreaParams {
	var ()
	return &ExploreAreaParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExploreAreaParamsWithTimeout creates a new ExploreAreaParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExploreAreaParamsWithTimeout(timeout time.Duration) *ExploreAreaParams {
	var ()
	return &ExploreAreaParams{

		timeout: timeout,
	}
}

// NewExploreAreaParamsWithContext creates a new ExploreAreaParams object
// with the default values initialized, and the ability to set a context for a request
func NewExploreAreaParamsWithContext(ctx context.Context) *ExploreAreaParams {
	var ()
	return &ExploreAreaParams{

		Context: ctx,
	}
}

// NewExploreAreaParamsWithHTTPClient creates a new ExploreAreaParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExploreAreaParamsWithHTTPClient(client *http.Client) *ExploreAreaParams {
	var ()
	return &ExploreAreaParams{
		HTTPClient: client,
	}
}

/*ExploreAreaParams contains all the parameters to send to the API endpoint
for the explore area operation typically these are written to a http.Request
*/
type ExploreAreaParams struct {

	/*Args
	  Area to be explored.

	*/
	Args *model.Area

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the explore area params
func (o *ExploreAreaParams) WithTimeout(timeout time.Duration) *ExploreAreaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the explore area params
func (o *ExploreAreaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the explore area params
func (o *ExploreAreaParams) WithContext(ctx context.Context) *ExploreAreaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the explore area params
func (o *ExploreAreaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the explore area params
func (o *ExploreAreaParams) WithHTTPClient(client *http.Client) *ExploreAreaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the explore area params
func (o *ExploreAreaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the explore area params
func (o *ExploreAreaParams) WithArgs(args *model.Area) *ExploreAreaParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the explore area params
func (o *ExploreAreaParams) SetArgs(args *model.Area) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *ExploreAreaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Args != nil {
		if err := r.SetBodyParam(o.Args); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
