// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// ExploreAreaReader is a Reader for the ExploreArea structure.
type ExploreAreaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExploreAreaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExploreAreaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewExploreAreaDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExploreAreaOK creates a ExploreAreaOK with default headers values
func NewExploreAreaOK() *ExploreAreaOK {
	return &ExploreAreaOK{}
}

/*ExploreAreaOK handles this case with default header values.

Report about found treasures.
*/
type ExploreAreaOK struct {
	Payload *model.Report
}

func (o *ExploreAreaOK) Error() string {
	return fmt.Sprintf("[POST /explore][%d] exploreAreaOK  %+v", 200, o.Payload)
}

func (o *ExploreAreaOK) GetPayload() *model.Report {
	return o.Payload
}

func (o *ExploreAreaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Report)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExploreAreaDefault creates a ExploreAreaDefault with default headers values
func NewExploreAreaDefault(code int) *ExploreAreaDefault {
	return &ExploreAreaDefault{
		_statusCode: code,
	}
}

/*ExploreAreaDefault handles this case with default header values.

- 422.1000: wrong coordinates

*/
type ExploreAreaDefault struct {
	_statusCode int

	Payload *model.Error
}

// Code gets the status code for the explore area default response
func (o *ExploreAreaDefault) Code() int {
	return o._statusCode
}

func (o *ExploreAreaDefault) Error() string {
	return fmt.Sprintf("[POST /explore][%d] exploreArea default  %+v", o._statusCode, o.Payload)
}

func (o *ExploreAreaDefault) GetPayload() *model.Error {
	return o.Payload
}

func (o *ExploreAreaDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
