// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// ListLicensesReader is a Reader for the ListLicenses structure.
type ListLicensesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListLicensesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListLicensesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListLicensesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListLicensesOK creates a ListLicensesOK with default headers values
func NewListLicensesOK() *ListLicensesOK {
	return &ListLicensesOK{}
}

/*ListLicensesOK handles this case with default header values.

List of issued licenses.
*/
type ListLicensesOK struct {
	Payload model.LicenseList
}

func (o *ListLicensesOK) Error() string {
	return fmt.Sprintf("[GET /licenses][%d] listLicensesOK  %+v", 200, o.Payload)
}

func (o *ListLicensesOK) GetPayload() model.LicenseList {
	return o.Payload
}

func (o *ListLicensesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListLicensesDefault creates a ListLicensesDefault with default headers values
func NewListLicensesDefault(code int) *ListLicensesDefault {
	return &ListLicensesDefault{
		_statusCode: code,
	}
}

/*ListLicensesDefault handles this case with default header values.

General errors using same model as used by go-swagger for validation errors.
*/
type ListLicensesDefault struct {
	_statusCode int

	Payload *model.Error
}

// Code gets the status code for the list licenses default response
func (o *ListLicensesDefault) Code() int {
	return o._statusCode
}

func (o *ListLicensesDefault) Error() string {
	return fmt.Sprintf("[GET /licenses][%d] listLicenses default  %+v", o._statusCode, o.Payload)
}

func (o *ListLicensesDefault) GetPayload() *model.Error {
	return o.Payload
}

func (o *ListLicensesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
