// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// ExploreAreaOKCode is the HTTP code returned for type ExploreAreaOK
const ExploreAreaOKCode int = 200

/*ExploreAreaOK Report about found treasures.

swagger:response exploreAreaOK
*/
type ExploreAreaOK struct {

	/*
	  In: Body
	*/
	Payload *model.Report `json:"body,omitempty"`
}

// NewExploreAreaOK creates ExploreAreaOK with default headers values
func NewExploreAreaOK() *ExploreAreaOK {

	return &ExploreAreaOK{}
}

// WithPayload adds the payload to the explore area o k response
func (o *ExploreAreaOK) WithPayload(payload *model.Report) *ExploreAreaOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the explore area o k response
func (o *ExploreAreaOK) SetPayload(payload *model.Report) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExploreAreaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *ExploreAreaOK) ExploreAreaResponder() {}

/*ExploreAreaDefault - 422.1000: wrong coordinates


swagger:response exploreAreaDefault
*/
type ExploreAreaDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewExploreAreaDefault creates ExploreAreaDefault with default headers values
func NewExploreAreaDefault(code int) *ExploreAreaDefault {
	if code <= 0 {
		code = 500
	}

	return &ExploreAreaDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the explore area default response
func (o *ExploreAreaDefault) WithStatusCode(code int) *ExploreAreaDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the explore area default response
func (o *ExploreAreaDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the explore area default response
func (o *ExploreAreaDefault) WithPayload(payload *model.Error) *ExploreAreaDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the explore area default response
func (o *ExploreAreaDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExploreAreaDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *ExploreAreaDefault) ExploreAreaResponder() {}

type ExploreAreaNotImplementedResponder struct {
	middleware.Responder
}

func (*ExploreAreaNotImplementedResponder) ExploreAreaResponder() {}

func ExploreAreaNotImplemented() ExploreAreaResponder {
	return &ExploreAreaNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.ExploreArea has not yet been implemented",
		),
	}
}

type ExploreAreaResponder interface {
	middleware.Responder
	ExploreAreaResponder()
}
