// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// ListLicensesOKCode is the HTTP code returned for type ListLicensesOK
const ListLicensesOKCode int = 200

/*ListLicensesOK List of issued licenses.

swagger:response listLicensesOK
*/
type ListLicensesOK struct {

	/*
	  In: Body
	*/
	Payload model.LicenseList `json:"body,omitempty"`
}

// NewListLicensesOK creates ListLicensesOK with default headers values
func NewListLicensesOK() *ListLicensesOK {

	return &ListLicensesOK{}
}

// WithPayload adds the payload to the list licenses o k response
func (o *ListLicensesOK) WithPayload(payload model.LicenseList) *ListLicensesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list licenses o k response
func (o *ListLicensesOK) SetPayload(payload model.LicenseList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListLicensesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = model.LicenseList{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *ListLicensesOK) ListLicensesResponder() {}

/*ListLicensesDefault General errors using same model as used by go-swagger for validation errors.

swagger:response listLicensesDefault
*/
type ListLicensesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewListLicensesDefault creates ListLicensesDefault with default headers values
func NewListLicensesDefault(code int) *ListLicensesDefault {
	if code <= 0 {
		code = 500
	}

	return &ListLicensesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list licenses default response
func (o *ListLicensesDefault) WithStatusCode(code int) *ListLicensesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list licenses default response
func (o *ListLicensesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list licenses default response
func (o *ListLicensesDefault) WithPayload(payload *model.Error) *ListLicensesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list licenses default response
func (o *ListLicensesDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListLicensesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *ListLicensesDefault) ListLicensesResponder() {}

type ListLicensesNotImplementedResponder struct {
	middleware.Responder
}

func (*ListLicensesNotImplementedResponder) ListLicensesResponder() {}

func ListLicensesNotImplemented() ListLicensesResponder {
	return &ListLicensesNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.ListLicenses has not yet been implemented",
		),
	}
}

type ListLicensesResponder interface {
	middleware.Responder
	ListLicensesResponder()
}
